# Generated by Django 4.1.1 on 2022-10-02 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Наименование учреждения')),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Наименование учреждения',
                'verbose_name_plural': 'Наименование учреждения',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Объект закупки')),
                ('slug', models.SlugField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Начальная цена контракта')),
                ('signed', models.DateField(auto_now=True)),
                ('returned', models.DateField(auto_now=True)),
                ('transferred', models.DateField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='registry.hospital', verbose_name='Наименование учреждения')),
            ],
            options={
                'verbose_name': 'Закупки',
                'verbose_name_plural': 'Закупки',
                'ordering': ('name', 'price'),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
